name: flutter_launcher_mcp
description: An MCP server for launching and managing Flutter applications.
version: 0.2.1
environment:
  sdk: ^3.9.0
dependencies:
  args: ^2.7.0
  async: ^2.13.0
  collection: ^1.19.1
  dart_mcp: ^0.3.3
  file: ^7.0.1
  path: ^1.9.1
  process: ^5.0.5
  stream_channel: ^2.1.4
  unified_analytics: ^8.0.5
  yaml: ^3.1.3
dev_dependencies:
  fake_async: ^1.3.3
  lints: ^6.0.0
  test: ^1.25.6
